import type { AuditDetails, CandlePoint, PrevDayLevels, ScanRow, SignalStatus, LevelTag } from "./types";
import { STATUS_RANK } from "./types";
import { emaSeries, emaSlope } from "./indicators";

export interface QualityEngineConfig { timeframeMinutes: 1 | 3 | 5; emaPeriod: number; volumeRefCandles: number; volumeRefMinimum: number; breakoutVolMin: number; nearLevelPct: number; minCandlesRequired: number; riskReward: number; slBufferPct: number; scanStartMinutes: number; }
const r2 = (n: number) => Math.round(n * 100) / 100;
const clamp = (n: number, lo: number, hi: number) => Math.max(lo, Math.min(hi, n));
const volumeTier = (x: number | null) => x == null ? null : x >= 6.5 ? "6.5x EXTREME" : x >= 4 ? "4x VERY HIGH" : x >= 2 ? "2x HIGH" : x >= 1.5 ? "1.5x STRONG" : "LOW";
function details(levels: PrevDayLevels, candles: CandlePoint[], emaNow: number | null): AuditDetails { return { pdh: levels.pdh, pdl: levels.pdl, prevClose: levels.prevClose, triggerType: null, triggerTime: null, triggerOpen: null, triggerHigh: null, triggerLow: null, triggerClose: null, triggerVolume: null, referenceVolume: null, volumeMultiple: null, volumeLabel: null, emaAtTrigger: null, emaNow, emaSlope: null, followThrough: [], confirmationTime: null, priceAtConfirmation: null, entry: null, stopLoss: null, target: null, riskReward: null, candlesAnalyzed: candles.length, lastCandleTime: candles[candles.length - 1]?.label ?? null, checks: [], failureNote: null }; }
function refVolume(vols: number[], idx: number, count: number, minimum: number): { reference: number | null; multiple: number | null } { const values = vols.slice(Math.max(0, idx - count), idx).filter(v => Number.isFinite(v) && v > 0); if (values.length < minimum) return { reference: null, multiple: null }; const reference = values.reduce((a, b) => a + b, 0) / values.length; return { reference, multiple: reference > 0 ? vols[idx] / reference : null }; }
function rankStatus(status: SignalStatus, side: "BUY" | "SELL") { if (status === "CONFIRMED") return side === "BUY" ? STATUS_RANK.CONFIRMED_PDH_BUY : STATUS_RANK.CONFIRMED_PDL_SELL; if (status === "SETUP") return STATUS_RANK.SETUP; if (status === "WATCH") return STATUS_RANK.WATCH; return STATUS_RANK.NONE; }

export function analyzeQualitySymbol(input: { symbol: string; timeframeMinutes: 1 | 3 | 5; candles: CandlePoint[]; warmup: CandlePoint[]; levels: PrevDayLevels; ltpOverride?: number | null }, cfg: QualityEngineConfig): ScanRow {
  const today = input.candles; const all = [...input.warmup, ...today]; const start = input.warmup.length; const tf = input.timeframeMinutes;
  const empty = (reason: string): ScanRow => ({ symbol: input.symbol, timeframeMinutes: tf, ltp: input.ltpOverride ?? today[today.length - 1]?.c ?? null, changePct: null, dayOpen: today[0]?.o ?? null, volumeMultiple: null, volumeLabel: null, ema20: null, emaBias: "-", pdh: input.levels.pdh, pdl: input.levels.pdl, level: "-", distancePct: null, setup: "NONE", status: "NONE", direction: "NONE", entry: null, stopLoss: null, target: null, reason, statusRank: STATUS_RANK.NONE, active: true, firstConfirmedAt: null, details: null });
  if (today.length < cfg.minCandlesRequired) return empty(`Waiting for first completed ${tf}-minute candle (${today.length}/${cfg.minCandlesRequired})`);
  const closes = all.map(c => c.c), highs = all.map(c => c.h), lows = all.map(c => c.l), vols = all.map(c => c.v); const ema = emaSeries(closes, cfg.emaPeriod); const last = all.length - 1; const emaNow = ema[last] ?? null; const ltp = input.ltpOverride ?? today[today.length - 1].c; const latestVm = refVolume(vols, last, cfg.volumeRefCandles, cfg.volumeRefMinimum);
  type Candidate = { side: "BUY" | "SELL"; level: "PDH" | "PDL"; idx: number; score: number; status: SignalStatus; active: boolean; details: AuditDetails; reason: string; entry: number | null; sl: number | null; target: number | null };
  let best: Candidate | null = null;
  for (const side of ["BUY", "SELL"] as const) {
    const isBuy = side === "BUY"; const levelTag: "PDH" | "PDL" = isBuy ? "PDH" : "PDL"; const level = isBuy ? input.levels.pdh : input.levels.pdl; let breakIdx = -1;
    for (let i = start; i < all.length; i++) { const prev = i === start ? input.levels.prevClose : closes[i - 1]; if ((isBuy && prev <= level && closes[i] > level) || (!isBuy && prev >= level && closes[i] < level)) { breakIdx = i; break; } }
    if (breakIdx < 0) { const distance = Math.abs((ltp - level) / level) * 100; const aligned = emaNow != null && (isBuy ? ltp >= emaNow : ltp <= emaNow); if (distance > cfg.nearLevelPct && !aligned) continue; const d = details(input.levels, all, emaNow); d.emaSlope = emaSlope(ema, last, 3); d.checks = [{ label: `${levelTag} valid`, ok: true, value: level.toFixed(2) }, { label: `${tf}M close beyond ${levelTag}`, ok: false, value: "not yet" }, { label: "20 EMA alignment", ok: aligned, value: emaNow == null ? "warming up" : aligned ? "aligned" : "conflict" }]; const candidate: Candidate = { side, level: levelTag, idx: -1, score: 25, status: "WATCH", active: true, details: d, reason: distance <= cfg.nearLevelPct ? `Near ${levelTag}; waiting for confirmed ${tf}M break` : `EMA aligned; watching ${levelTag}`, entry: null, sl: null, target: null }; if (!best || candidate.score > best.score) best = candidate; continue; }
    const c = all[breakIdx]; const range = Math.max(0, c.h - c.l); const bodyRatio = range > 0 ? Math.abs(c.c - c.o) / range : 0; const closeLocation = range > 0 ? (isBuy ? (c.c - c.l) / range : (c.h - c.c) / range) : 0; const vm = refVolume(vols, breakIdx, cfg.volumeRefCandles, cfg.volumeRefMinimum); const emaAt = ema[breakIdx] ?? null; const aligned = emaAt != null && (isBuy ? c.c > emaAt : c.c < emaAt);
    const from = Math.max(start, breakIdx - 10); let sum = 0, n = 0; for (let j = from; j < breakIdx; j++) { sum += Math.max(0, highs[j] - lows[j]); n++; } const avgRange = n ? sum / n : 0; const rangeExpansion = avgRange > 0 ? range / avgRange : 0; const strongCandle = (isBuy ? c.c > c.o : c.c < c.o) && bodyRatio >= 0.5 && closeLocation >= 0.6; const volumeOK = (vm.multiple ?? 0) >= cfg.breakoutVolMin; const hardConfirm = volumeOK && aligned && strongCandle;
    let failIdx = -1; for (let j = breakIdx + 1; j < all.length; j++) { if (isBuy ? closes[j] < level : closes[j] > level) { failIdx = j; break; } } const status: SignalStatus = failIdx >= 0 ? "WATCH" : hardConfirm ? "CONFIRMED" : "SETUP";
    const parts = c.label.split(":"); const elapsed = Number(parts[0]) * 60 + Number(parts[1]) - cfg.scanStartMinutes; const volumeScore = (vm.multiple ?? 0) >= 6.5 ? 20 : (vm.multiple ?? 0) >= 4 ? 18 : (vm.multiple ?? 0) >= 2 ? 15 : (vm.multiple ?? 0) >= 1.5 ? 10 : 0; const penetration = clamp(Math.abs((c.c - level) / level) * 15, 0, 15); const candleScore = clamp(bodyRatio * 15, 0, 15); const closeScore = clamp(closeLocation * 10, 0, 10); const emaScore = clamp((emaAt && emaAt > 0 ? Math.abs((c.c - emaAt) / emaAt) * 15 : 0), 0, 15); const rangeScore = rangeExpansion >= 2 ? 10 : rangeExpansion >= 1.75 ? 9 : rangeExpansion >= 1.5 ? 8 : rangeExpansion >= 1.3 ? 6 : rangeExpansion >= 1.1 ? 3 : 0; const timingScore = elapsed <= 5 ? 10 : elapsed <= 10 ? 9 : elapsed <= 15 ? 8 : elapsed <= 20 ? 6 : elapsed <= 30 ? 4 : elapsed <= 45 ? 2 : 0; const compressionScore = rangeExpansion >= 1.5 ? 5 : rangeExpansion >= 1.3 ? 2 : 0; const qualityScore = Math.round(clamp(volumeScore + penetration + candleScore + closeScore + emaScore + rangeScore + timingScore + compressionScore, 0, 100));
    const d = details(input.levels, all, emaNow); d.triggerType = `${levelTag} ${isBuy ? "BREAKOUT" : "BREAKDOWN"} ${tf}M`; d.triggerTime = c.label; d.triggerOpen = c.o; d.triggerHigh = c.h; d.triggerLow = c.l; d.triggerClose = c.c; d.triggerVolume = c.v; d.referenceVolume = vm.reference; d.volumeMultiple = vm.multiple; d.volumeLabel = volumeTier(vm.multiple); d.emaAtTrigger = emaAt; d.emaSlope = emaSlope(ema, breakIdx, 3); d.checks = [{ label: `${levelTag} close break`, ok: true, value: `${c.c.toFixed(2)} ${isBuy ? ">" : "<"} ${level.toFixed(2)}` }, { label: `Volume >= ${cfg.breakoutVolMin}x`, ok: volumeOK, value: vm.multiple == null ? "no reference" : `${vm.multiple.toFixed(2)}x` }, { label: "Price vs EMA20", ok: aligned, value: emaAt == null ? "warming up" : aligned ? "aligned" : "conflict" }, { label: "Candle quality", ok: strongCandle, value: `${Math.round(bodyRatio * 100)}% body / ${Math.round(closeLocation * 100)}% close` }, { label: "Range expansion", ok: rangeExpansion >= 1.3, value: `${rangeExpansion.toFixed(2)}x` }]; if (failIdx >= 0) d.failureNote = `${levelTag} break failed at ${all[failIdx].label}`;
    let entry: number | null = null, sl: number | null = null, target: number | null = null; if (status === "CONFIRMED") { entry = c.c; const structural = isBuy ? Math.min(c.l, level) : Math.max(c.h, level); const buffer = level * cfg.slBufferPct / 100; sl = isBuy ? structural - buffer : structural + buffer; const risk = Math.abs(entry - sl); target = isBuy ? entry + risk * cfg.riskReward : entry - risk * cfg.riskReward; d.confirmationTime = c.label; d.priceAtConfirmation = entry; d.entry = r2(entry); d.stopLoss = r2(sl); d.target = r2(target); d.riskReward = cfg.riskReward; }
    const reason = failIdx >= 0 ? `${levelTag} break failed — closed back ${isBuy ? "below" : "above"} ${levelTag}` : status === "CONFIRMED" ? `${levelTag} ${isBuy ? "breakout" : "breakdown"} + ${vm.multiple?.toFixed(1) ?? "?"}x volume + EMA20 aligned + PRIME ${qualityScore}/100` : `${levelTag} break detected; waiting for volume/EMA confirmation`;
    const candidate: Candidate = { side, level: levelTag, idx: breakIdx, score: qualityScore + (status === "CONFIRMED" ? 20 : status === "SETUP" ? 8 : 0), status, active: failIdx < 0, details: d, reason, entry, sl, target }; if (!best || candidate.score > best.score) best = candidate;
  }
  const changePct = input.levels.prevClose > 0 ? ((ltp - input.levels.prevClose) / input.levels.prevClose) * 100 : null; const latestEma = emaNow == null ? null : r2(emaNow); const latestBias = emaNow == null ? "-" : ltp >= emaNow ? "ABOVE EMA20" : "BELOW EMA20";
  if (!best) return { ...empty("No Prime Technical structure"), ltp: r2(ltp), changePct: changePct == null ? null : r2(changePct), volumeMultiple: latestVm.multiple == null ? null : r2(latestVm.multiple), volumeLabel: volumeTier(latestVm.multiple), ema20: latestEma, emaBias: latestBias };
  const levelPrice = best.level === "PDH" ? input.levels.pdh : input.levels.pdl; const distancePct = ((ltp - levelPrice) / levelPrice) * 100;
  return { symbol: input.symbol, timeframeMinutes: tf, ltp: r2(ltp), changePct: changePct == null ? null : r2(changePct), dayOpen: r2(today[0].o), volumeMultiple: best.details.volumeMultiple ?? latestVm.multiple, volumeLabel: best.details.volumeLabel ?? volumeTier(latestVm.multiple), ema20: latestEma, emaBias: latestBias, pdh: input.levels.pdh, pdl: input.levels.pdl, level: best.level as LevelTag, distancePct: r2(distancePct), setup: best.level === "PDH" ? "PDH_BUY" : "PDL_SELL", status: best.status, direction: best.side, entry: best.entry, stopLoss: best.sl, target: best.target, reason: best.reason, statusRank: rankStatus(best.status, best.side), active: best.active, firstConfirmedAt: best.details.confirmationTime, details: best.details };
}
