/**
 * NSE equity universe — NIFTY 500 coverage (large + mid + small caps, F&O heavy).
 * Symbols are NSE trading symbols; Upstox instrument keys (NSE_EQ|ISIN) are
 * resolved server-side and cached. Unresolvable symbols are skipped gracefully.
 */

const RAW_UNIVERSE = `
ADANIENT ADANIPORTS APOLLOHOSP ASIANPAINT AXISBANK BAJAJ-AUTO BAJFINANCE
BAJAJFINSV BEL BHARTIARTL BPCL BRITANNIA CIPLA COALINDIA DRREDDY EICHERMOT
ETERNAL GRASIM HCLTECH HDFCBANK HDFCLIFE HEROMOTOCO HINDALCO HINDUNILVR
ICICIBANK INDUSINDBK INFY ITC JIOFIN JSWSTEEL KOTAKBANK LT M&M MARUTI
NESTLEIND NTPC ONGC POWERGRID RELIANCE SBILIFE SBIN SHRIRAMFIN SUNPHARMA
TATACONSUM TATAMOTORS TATASTEEL TCS TECHM TITAN TRENT ULTRACEMCO WIPRO
ADANIGREEN ADANIPOWER ATGL AMBUJACEM AUROPHARMA BANKBARODA BOSCHLTD CANBK
CHOLAFIN DABUR DLF GAIL GODREJCP HAVELLS HINDZINC ICICIGI ICICIPRULI INDIGO
IRCTC LODHA LTIM MANKIND MARICO NAUKRI PEL PIDILITIND PNB SHREECEM SIEMENS
TORNTPHARM TVSMOTOR UPL VEDL ZYDUSLIFE ABB BALKRISIND BERGEPAINT COLPAL
CONCOR CUMMINSIND GODREJPROP HDFCAMC INDIHOTEL LTTS MUTHOOTFIN NMDC
OBEROIRLTY OFSS PAGEIND POLYCAB SBICARD SOLARINDS TATAPOWER VARROC
AARTIIND ABBOTINDIA ABFRL ACC AIAENG AJANTPHARM ALKEM AMARAJABAT APARINDS
APOLLOTYRE ASHOKLEY ASTRAL AUBANK BALRAMCHIN BANDHANBNK BATAINDIA BEML
BHARATFORG BHEL BIRLACORPN BLUEDART BRIGADE CANFINHOME CARBORUNIV CASTROLIND
CESC CGPOWER CHAMBLFERT CHOLAHLDNG COFORGE COROMANDEL CROMPTON CUB CYIENT
DEEPAKNTR DEVYANI DIXON DOMS ELGIEQUIP EMAMILTD ENDURANCE ESCORTS EXIDEIND
FEDERALBNK FINCABLES FORTIS GLAND GLENMARK GNFC GODFRYPHLP GODREJAGROVET
GODREJIND GRANULES GUJGASLTD HAL HAPPSTMNDS HFCL HINDPETRO HONAUT
IDFCFIRSTB IEX IGL INDIACEM INDIANB INDUSTOWER IRB IRFC ITI JBCHEPHARM
JINDALSTEL JSL JUBLFOOD JUBLINGREA KALYANKJIL KANSAINER KARURVYSYA KEI
KPITTECH LALPATHLAB LAURUSLABS LICHSGFIN LINDEINDIA LUPIN M&MFIN MANAPPURAM
MASTEK MAXHEALTH MCX METROBRAND MFSL MGL MOTHERSON MPHASIS MRF NATCOPHARM
NATIONALUM NAVINFLUOR NCC NHPC NLCINDIA OIL PAYTM PERSISTENT PETRONET PFC
PHOENIXLTD PIIND PNBHOUSING POONAWALLA PPLPHARMA PRESTIGE RAJESHEXPO
RAMCOCEM RBLBANK RECLTD REDINGTON RELAXO SAIL SCHAEFFLER SONACOMS
STARHEALTH SUDARSCHEM SUPREMEIND SYNGENE TATACHEM TATACOMM TATAELXSI
TEJASNET THERMAX TIMKEN TRIDENT TVSSCS UCOBANK UJJIVANSFB UNIONBANK
UNOMINDA UTIAMC VGUARD VOLTAS WELCORP WHIRLPOOL YESBANK ZEEL ZENSARTECH
360ONE AAVAS AFFLE AMBER ANGELONE APLAPOLLO APTUS ARVIND ASAHIINDIA
AVANTIFEED BALAMINES BIKAJI BIOCON BLS BSOFT CAMPUS CCL CDSL CEATLTD
CENTRALBK CENTURYPLY CERA CLEAN CRISIL DATAPATTNS DEEPAKFERT DELHIVERY
ECLERX EIDPARRY EIHOTEL EQUITASBNK FDC FINPIPE FLUOROCHEM GESHIP GICRE
GILLETTE GLAXO GMDCLTD GMRINFRA GRAPHITE GRINDWELL GSPL GUJALKALI HBLPOWER
HINDCOPPER HOMEFIRST IDBI IIFL INDIAMART INDIGOPNTS INFIBEAM INOXWIND
INTELLECT IPCALAB IREDA JKCEMENT JKTYRE JMFINANCIL JPPOWER JSWENERGY
JYOTHYLAB KAJARIACER KEC KRBL KSB LATENTVIEW LEMONTREE LUXIND MAHABANK
MANINFRA MARKSANS MAZAGON MEDANTA MMTC MOIL MRPL NALCO NBCC NETWORK18
NITINSPIN NUVOCO NYKAA OLECTRA PATANJALI PCBL PFIZER PGEL PGHH PNCINFRA
POLICYBZR PRSMJOHNSN PVRINOX QUESS RADICO RAIN RKFORGE RATNAMANI RAYMOND
RCF RENUKA RITES ROUTE RVNL SAPPHIRE SARDAEN SAREGAMA SCHNEIDER SHOPERSTOP
SHYAMMETL SIS SOBHA SPANDANA SRF STAR SUNDRMFAST SUNTV SUPRAJIT SUVENPHAR
SWANENERGY SYMPHONY TANLA TARSONS TATAMETALI THYROCARE TIPSINDLTD TITAGARH
TORNTPOWER TRIL TRIVENI TTML TV18BRDCST VAIBHAVGBL VAKRANGEE VESUVIUS
VINATIORGA VIPIND VMART VSTIND WELSPUNIND WESTLIFE WOCKHARDT ZYDUSWELL
ABCAPITAL BAJAJELEC CEAT CAMS CAPLIPOINT CELLO CIGNITITEC CRAFTSMAN EASEMYTRIP
FACT FIVESTAR GRSE HGS HIKAL INDPRUD JSLHISAR KIMS KNRCON MAHLIFE MAHSCOOTER
MOTILALOFS NAVA NESCO PILANIINVS POLICYBAZAAR POWERINDIA PRAJIND RTNINDIA
SANOFI SASKEN SHARDACROP SUNTECK TECHNOE TVSHLTD UTIAMC VRLLOG ZFCVINDIA
`;

const seen = new Set<string>();

/** Deduplicated, sorted universe of NSE trading symbols. */
export const UNIVERSE: string[] = RAW_UNIVERSE.split(/\s+/)
  .map((s) => s.trim().toUpperCase())
  .filter((s) => {
    if (!s || seen.has(s)) return false;
    seen.add(s);
    return true;
  })
  .sort();

export const UNIVERSE_SIZE = UNIVERSE.length;
