/**
 * NSE F&O stock universe.
 *
 * This scanner intentionally excludes the broader NIFTY 500 universe and
 * scans only stocks that are currently represented in the NSE equity F&O
 * segment. The list is kept as trading symbols because the scanner analyzes
 * the underlying NSE_EQ candles, not futures/options candles.
 *
 * Source cross-check: current NSE F&O stock lists, including the active
 * derivatives universe published by market-data providers. Keep this list
 * refreshed when NSE adds/removes F&O underlyings.
 */

const RAW_UNIVERSE = `
360ONE ABB ABCAPITAL ADANIENSOL ADANIENT ADANIGREEN ADANIPORTS ADANIPOWER
ALKEM AMBER AMBUJACEM ANGELONE APLAPOLLO APOLLOHOSP ASHOKLEY ASIANPAINT
ASTRAL AUBANK AUROPHARMA AXISBANK BAJAJ-AUTO BAJAJFINSV BAJAJHLDNG BAJFINANCE
BANDHANBNK BANKBARODA BANKINDIA BDL BEL BHARATFORG BHARTIARTL BHEL BIOCON
BLUESTARCO BOSCHLTD BPCL BRITANNIA BSE CAMS CANBK CDSL CGPOWER CHOLAFIN CIPLA
COALINDIA COCHINSHIP COFORGE COLPAL CONCOR CROMPTON CUMMINSIND DABUR DALBHARAT
DELHIVERY DIVISLAB DIXON DLF DMART DRREDDY EICHERMOT ETERNAL FEDERALBNK FORCEMOT
FORTIS GAIL GLENMARK GMRAIRPORT GODFRYPHLP GODREJCP GODREJPROP GRASIM HAL HAVELLS
HCLTECH HDFCAMC HDFCBANK HDFCLIFE HEROMOTOCO HINDALCO HINDPETRO HINDUNILVR HINDZINC
HYUNDAI ICICIBANK ICICIGI ICICIPRULI IDEA IDFCFIRSTB IEX INDHOTEL INDIANB INDIGO
INDUSINDBK INDUSTOWER INFY INOXWIND IOC IREDA IRFC ITC JINDALSTEL JIOFIN JSWENERGY
JSWSTEEL JUBLFOOD KALYANKJIL KAYNES KEI KFINTECH KOTAKBANK KPITTECH LAURUSLABS
LICHSGFIN LICI LODHA LT LTF LTM LUPIN M&M MANAPPURAM MANKIND MARICO MARUTI
MAXHEALTH MAZDOCK MCX MFSL MOTHERSON MOTILALOFS MPHASIS MUTHOOTFIN NAM-INDIA NATIONALUM
NAUKRI NBCC NESTLEIND NHPC NMDC NTPC NYKAA OBEROIRLTY OFSS OIL ONGC PAGEIND PATANJALI
PAYTM PERSISTENT PETRONET PFC PGEL PHOENIXLTD PIDILITIND PIIND PNB PNBHOUSING POLICYBZR
POLYCAB POWERGRID POWERINDIA PREMIERENE PRESTIGE RBLBANK RECLTD RELIANCE RVNL SAIL SBICARD
SBILIFE SBIN SHREECEM SHRIRAMFIN SIEMENS SOLARINDS SONACOMS SRF SUNPHARMA SUPREMEIND
SUZLON SWIGGY TATACONSUM TATAELXSI TATAPOWER TATASTEEL TCS TECHM TIINDIA TITAN TMPV
TORNTPHARM TRENT TVSMOTOR ULTRACEMCO UNIONBANK UNITDSPR UNOMINDA UPL VBL VEDL VMM VOLTAS
WAAREEENER WIPRO YESBANK ZYDUSLIFE
`;

const seen = new Set<string>();

/** Deduplicated, sorted NSE F&O stock universe. */
export const UNIVERSE: string[] = RAW_UNIVERSE.split(/\s+/)
  .map((s) => s.trim().toUpperCase())
  .filter((s) => {
    if (!s || seen.has(s)) return false;
    seen.add(s);
    return true;
  })
  .sort();

export const UNIVERSE_SIZE = UNIVERSE.length;
